# Generated by Django 5.1.15 on 2026-04-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Profile photo for the sidebar card', upload_to='about/'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Short tagline shown on profile card', max_length=300),
        ),
    ]
