# Generated by Django 5.1.15 on 2026-04-16 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniAppCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'mini app categories',
            },
        ),
        migrations.CreateModel(
            name='MiniApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('template_name', models.CharField(blank=True, help_text="Template path, e.g. 'miniapps/nuclear-decay.html'. Leave blank to use miniapps/<slug>.html.", max_length=200)),
                ('thumbnail', models.CharField(blank=True, help_text='Emoji or icon class shown on the lab card.', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('embed_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apps', to='miniapps.miniappcategory')),
            ],
        ),
    ]
