# Generated by Django 5.1.15 on 2026-04-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miniapps", "0003_seed_hydraulics_lab"),
    ]

    operations = [
        migrations.CreateModel(
            name="MiniAppTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="miniapp",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="miniapps", to="miniapps.miniapptag"),
        ),
    ]
