# Generated by Django 5.1.15 on 2026-04-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_created_by_post_post_type_alter_post_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL (e.g. https://www.youtube.com/watch?v=... or https://youtu.be/...)', max_length=300),
        ),
    ]
