# Generated by Django 5.1.15 on 2026-04-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lqip',
            field=models.TextField(blank=True, editable=False, help_text='Auto-generated low-quality image placeholder (base64 data URI).'),
        ),
    ]
