# Generated by Django 5.1.15 on 2026-04-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(choices=[('post', 'Blog Post'), ('milestone', 'Milestone'), ('birthday', 'Birthday'), ('custom', 'Custom')], default='custom', max_length=30),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='icon',
            field=models.CharField(blank=True, help_text='CSS class for icon display', max_length=50),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Falls back to linked post image', null=True, upload_to='timeline/thumbs/%Y/'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='description',
            field=models.TextField(blank=True, help_text='Short text for the card'),
        ),
    ]
