# Generated by Django 5.1.15 on 2026-04-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_timelineevent_event_type_timelineevent_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(choices=[('snap', 'Snap'), ('post', 'Blog Post'), ('milestone', 'Milestone'), ('birthday', 'Birthday'), ('custom', 'Custom')], default='custom', max_length=30),
        ),
    ]
